spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/freelancer'
    username: freelancer_service
    password: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create'
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoint:
    health:
      enabled: true
  security:
    enabled: false